2021-07-13 09:24:11,017 - instabot version: 0.117.0 (bot) - INFO - Instabot version: 0.117.0 Started
2021-07-13 09:24:11,018 - instabot version: 0.117.0 (bot) - DEBUG - Bot imported from C:\Users\hlo\AppData\Local\Programs\Python\Python39\lib\site-packages\instabot\bot\bot.py
2021-07-13 09:24:11,101 - instabot version: 0.117.0 (api_login) - INFO - Not yet logged in starting: PRE-LOGIN FLOW!
2021-07-13 09:24:11,462 - instabot version: 0.117.0 (api) - DEBUG - POST to endpoint: accounts/get_prefill_candidates/ returned response: <Response [200]>
2021-07-13 09:24:11,815 - instabot version: 0.117.0 (api) - DEBUG - POST to endpoint: qe/sync/ returned response: <Response [200]>
2021-07-13 09:24:12,160 - instabot version: 0.117.0 (api) - DEBUG - POST to endpoint: launcher/sync/ returned response: <Response [200]>
2021-07-13 09:24:12,494 - instabot version: 0.117.0 (api) - DEBUG - POST to endpoint: accounts/contact_point_prefill/ returned response: <Response [200]>
2021-07-13 09:24:16,609 - instabot version: 0.117.0 (api) - DEBUG - POST to endpoint: accounts/login/ returned response: <Response [400]>
2021-07-13 09:24:16,609 - instabot version: 0.117.0 (api) - DEBUG - Responsecode indicates error; response content: b'{"message":"The password you entered is incorrect. Please try again.","invalid_credentials":true,"error_title":"Incorrect password","buttons":[{"title":"Try Again","action":"dismiss"}],"status":"fail","error_type":"bad_password"}'
2021-07-13 09:24:16,609 - instabot version: 0.117.0 (api) - ERROR - Request returns 400 error!
2021-07-13 09:24:16,610 - instabot version: 0.117.0 (api) - INFO - Instagram's error message: The password you entered is incorrect. Please try again.
2021-07-13 09:24:16,611 - instabot version: 0.117.0 (api) - INFO - Error type: bad_password
2021-07-13 09:24:16,611 - instabot version: 0.117.0 (api) - ERROR - Failed to login go to instagram and change your password
2021-07-13 09:24:16,612 - instabot version: 0.117.0 (api) - INFO - Username or password is incorrect.
2021-07-13 09:25:37,328 - instabot version: 0.117.0 (bot) - INFO - Instabot version: 0.117.0 Started
2021-07-13 09:25:37,329 - instabot version: 0.117.0 (bot) - DEBUG - Bot imported from C:\Users\hlo\AppData\Local\Programs\Python\Python39\lib\site-packages\instabot\bot\bot.py
2021-07-13 09:25:37,392 - instabot version: 0.117.0 (api_login) - INFO - Not yet logged in starting: PRE-LOGIN FLOW!
2021-07-13 09:25:37,793 - instabot version: 0.117.0 (api) - DEBUG - POST to endpoint: accounts/get_prefill_candidates/ returned response: <Response [429]>
2021-07-13 09:25:37,793 - instabot version: 0.117.0 (api) - DEBUG - Responsecode indicates error; response content: b'{"message":"Please wait a few minutes before you try again.","status":"fail"}'
2021-07-13 09:25:37,799 - instabot version: 0.117.0 (api) - ERROR - Request returns 429 error!
2021-07-13 09:25:37,800 - instabot version: 0.117.0 (api) - WARNING - That means 'too many requests'. I'll go to sleep for 5 minutes.
