2021-07-13 09:25:37,328 - instabot version: 0.117.0 (bot) - INFO - Instabot version: 0.117.0 Started
2021-07-13 09:25:37,329 - instabot version: 0.117.0 (bot) - DEBUG - Bot imported from C:\Users\hlo\AppData\Local\Programs\Python\Python39\lib\site-packages\instabot\bot\bot.py
2021-07-13 09:25:37,392 - instabot version: 0.117.0 (api_login) - INFO - Not yet logged in starting: PRE-LOGIN FLOW!
2021-07-13 09:25:37,793 - instabot version: 0.117.0 (api) - DEBUG - POST to endpoint: accounts/get_prefill_candidates/ returned response: <Response [429]>
2021-07-13 09:25:37,793 - instabot version: 0.117.0 (api) - DEBUG - Responsecode indicates error; response content: b'{"message":"Please wait a few minutes before you try again.","status":"fail"}'
2021-07-13 09:25:37,799 - instabot version: 0.117.0 (api) - ERROR - Request returns 429 error!
2021-07-13 09:25:37,800 - instabot version: 0.117.0 (api) - WARNING - That means 'too many requests'. I'll go to sleep for 5 minutes.
